### ISSUE TITLE
Ion specification name conflict

### ISSUE THREAD

**Issue by lhazlewood** [jjenkov/iap-tools-java#1]
Hi there!

I just wanted to let you know about this:

http://ionwg.github.io/draft-ion.html

which has been in development for over a year now.  I thought I'd point it out in case you didn't want a name conflict with your concept of 'ion'.

Cheers!

**Comment by jjenkov** [comment]
Thank you for notifying us about the potential name conflict. Looks like
your data
format, right?

We did Google quite a bit before settling on ION, and there was no competing
formats online at that time. In other words, your data format did not come
up.
Nor did Amazon's internal, similar format named ION - which somebody also
told us about later.

It is the same with IAP - the name of our network protocol. There is
something
called Internet Alarm Protocol too, and apparently Apple has something
with Ipod A... (something) ... Protocol too.

It is not possible to have completely unique names online anymore. There
is always someone who has a small project using the same acronyms -
even if you don't find them in Google when you first search.

We will stick with IAP / ION for now. Maybe we find a better name in
the future.

- Jakob Jenkov



On Wed, Feb 3, 2016 at 10:59 PM, Les Hazlewood <notifications@github.com>
wrote:

> Hi there!
>
> I just wanted to let you know about this:
>
> http://ionwg.github.io/draft-ion.html
>
> which has been in development for over a year now. I thought I'd point it
> out in case you didn't want a name conflict with your concept of 'ion'.
>
> Cheers!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jjenkov/iap-tools-java/issues/1>.
>



-- 
Jakob Jenkov
jakob@jenkov.com
Founder, CEO

Jenkov Aps
http://jenkov.com
http://tutorials.jenkov.com

http://feeds2.feedburner.com/jenkov-com
